#!/usr/bin/env bash

HOME=/home/$(whoami)
FOLDER=proy/repos/teuton.d/teuton-get
RUBY_VERSION=$(cat $HOME/$FOLDER/.ruby-version)
RUBY=$HOME/.rbenv/versions/$RUBY_VERSION/bin/ruby
APP=$HOME/$FOLDER/bin/teutonget

$RUBY $APP $1 $2 $3 $4 $5
